### ISSUE TITLE
Updated libraries do not have SetBuffer

### ISSUE THREAD

**Issue by zachmatts10** [sciguy14/WordClock#1]
Hi, I believe I updated your code to work with the newest libraries but I am struggling with the setDisplay function. It appears to get hung up on the SetBuffer portion. I am a coding novice so any advice is greatly appreciated.

Traceback (most recent call last):
  File "WordClock.py", line 443, in <module>
    run("time_test", modifiers=["birthday"])
  File "WordClock.py", line 390, in run
    setDisplay(getTimeWords(datetime(2016, 01, 01, h, m, 0)),primary_color)
  File "WordClock.py", line 355, in setDisplay
    matrix.SetBuffer(frame_buff)
AttributeError: 'rgbmatrix.core.RGBMatrix' object has no attribute 'SetBuffer'

**Comment by sciguy14** [comment]
Hi @zachmatts10 

I was bored this weekend, so I went ahead and modernized all the software in this repo. Go take a peek at the README and follow the new instructions. You'll see that everything is now configured and tested to use @hzeller's `rpi-rgb-led-matrix` library, instead of the unmaintained Adafruit fork that was previously used. As part of that move, I fixed the `SetBuffer` issue you encountered by instead using numpy arrays and the `SetImage()` functionality of the led matrix python bindings. As part of this modernization, I've also moved everything to python3, and to the latest version of Raspbian Lite (Buster). I've tested all this and confirmed that it works well on my wordclock. In fact, I believe I was able to make the color fades a bit smoother, and these changes also reduced LED flicker.

If you run into issues with my changes, let me know. Otherwise, please feel free to close this issue. Thanks!

**Comment by sciguy14** [comment]
Haven't heard back, but I do believe that the latest release fixes this. Closing.

**Comment by zachmatts10** [comment]
Hi, my apologies. Yes, everything works great! Thanks for updating this!!
